version: '3'

services:
  alumni_postgres:
    container_name: alumni_postgres
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql

  alumni_postgres_test:
    container_name: alumni_postgres_test
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
      - POSTGRES_DB=${DB_NAME_TEST}
